FROM node:lts-alpine

ENV NODE_ENV=production

RUN apk add --no-cache git

RUN npm install -g pnpm --loglevel=error

WORKDIR /app

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --prod

COPY . .

CMD ["node", "./index.mjs"]